repos:
- repo: local
  hooks:
  - id: ruff
    name: ruff-format
    stages: [pre-commit]
    language: system
    entry: poetry run ruff format .
    types: [python]

  - id: ruff
    name: ruff-check
    stages: [pre-commit]
    language: system
    entry: poetry run ruff check . --fix
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [pre-commit]
    language: system
    entry: poetry run mypy
    types: [python]
    require_serial: true

  - id: pytest
    name: pytest
    stages: [pre-commit, pre-push]
    language: system
    entry: poetry run pytest --cov
    types: [python]
    pass_filenames: false
